// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  sky_d_ive: dynamic(() => import("./SkyDIve")),
};
